language: python

python:
 - "3.8"
 - "3.9"
 - "3.10"
os:
  - linux
dist: focal

script: pytest
before_script:
 - python -m pip install -r build_requirements.txt
 - python setup.py build_ext --inplace