language: python

python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
os:
  - linux

script: pytest
before_script:
 - python -m pip install setuptools cython numpy numba
 - python setup.py build_ext --inplace