name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.0a1

      - name: Build wheels
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: "<=3.9"
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
