name: Build

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
